pipeline {
    agent any

    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose the Terraform action'
        )
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {

        stage('GIT_CHECKOUT') {
            steps {
                git url: 'https://github.com/Gotoman12/DevopsPractice-Python-chees.git', branch: 'Iac'
            }
        }

        stage('terraform-plan') {
            steps {
                sh '''
                  cd iac
                  terraform init
                  terraform plan -out=tfplan
                  terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }

        stage('terraform-approval') {
            steps {
                script {
                    def plan = readFile 'iac/tfplan.txt'
                    input(
                        message: "Do you want to proceed with Terraform?",
                        parameters: [
                            text(
                                name: 'planReview',
                                description: 'Review Terraform execution plan',
                                defaultValue: plan
                            )
                        ]
                    )
                }
            }
        }

        stage('Apply or Destroy') {
            when {
                expression {
                    params.terraformAction in ['apply', 'destroy']
                }
            }
            steps {
                script {
                    if (params.terraformAction == 'apply') {
                        sh 'cd iac && terraform apply -input=false tfplan'
                    } else {
                        sh 'cd iac && terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}
